file_around_pit: /home/hash/catkin_ws/src/path_location_mapping.csv
file_to_pit: /home/hash/catkin_ws/src/lander_to_pit_trajectory.csv
lunar_env_path: /home/hash/Documents/lunar-env
manual_override: false
map_location: /home/ayush not used /catkin_ws/src/waypoint_pit_planner/src/mapp.csv
map_server: {frame_id: map}
move_base:
  TebLocalPlannerROS:
    acc_lim_theta: 0.5
    acc_lim_x: 0.5
    allow_init_with_backwards_motion: false
    costmap_converter:
      CostmapToLinesDBSRANSAC: {cluster_max_distance: 0.4, cluster_min_pts: 2, convex_hull_min_pt_separation: 0.1,
        ransac_convert_outlier_pts: true, ransac_filter_remaining_outlier_pts: false,
        ransac_inlier_distance: 0.15, ransac_min_inliers: 10, ransac_no_iterations: 1500,
        ransac_remainig_outliers: 3}
    costmap_converter_plugin: costmap_converter::CostmapToLinesDBSRANSAC
    costmap_converter_rate: 5
    costmap_converter_spin_thread: true
    costmap_obstacles_behind_robot_dist: 1.5
    delete_detours_backwards: true
    dt_hysteresis: 0.1
    dt_ref: 0.3
    dynamic_obstacle_inflation_dist: 0.6
    enable_homotopy_class_planning: true
    enable_multithreading: true
    exact_arc_length: false
    feasibility_check_no_poses: 5
    footprint_model: {type: point}
    free_goal_vel: false
    global_plan_overwrite_orientation: true
    global_plan_prune_distance: 1
    global_plan_viapoint_sep: -1
    h_signature_prescaler: 0.5
    h_signature_threshold: 0.1
    include_costmap_obstacles: true
    include_dynamic_obstacles: true
    inflation_dist: 0.5
    max_global_plan_lookahead_dist: 1
    max_number_classes: 4
    max_ratio_detours_duration_best_duration: 3.0
    max_samples: 500
    max_vel_theta: 3.036
    max_vel_x: 0.7
    max_vel_x_backwards: 0.7
    max_vel_y: 0
    min_obstacle_dist: 0.5
    min_turning_radius: 0.01
    no_inner_iterations: 5
    no_outer_iterations: 4
    obstacle_cost_exponent: 4
    obstacle_heading_threshold: 0.45
    obstacle_poses_affected: 15
    odom_topic: odometry_ground_truth
    optimization_activate: true
    optimization_verbose: false
    oscillation_filter_duration: 10
    oscillation_omega_eps: 0.1
    oscillation_recovery: true
    oscillation_recovery_min_duration: 10
    oscillation_v_eps: 0.1
    penalty_epsilon: 0.1
    publish_feedback: false
    roadmap_graph_area_length_scale: 1.0
    roadmap_graph_area_width: 5
    roadmap_graph_no_samples: 15
    selection_alternative_time_cost: false
    selection_cost_hysteresis: 1.0
    selection_obst_cost_scale: 100.0
    selection_prefer_initial_plan: 0.9
    shrink_horizon_backup: true
    shrink_horizon_min_duration: 10
    switching_blocking_period: 0.0
    teb_autosize: true
    viapoints_all_candidates: true
    visualize_hc_graph: false
    visualize_with_time_as_z_axis_scale: false
    weight_acc_lim_theta: 1
    weight_acc_lim_x: 1
    weight_adapt_factor: 2
    weight_dynamic_obstacle: 10
    weight_dynamic_obstacle_inflation: 0.2
    weight_inflation: 0.2
    weight_kinematics_forward_drive: 1
    weight_kinematics_nh: 1000
    weight_kinematics_turning_radius: 1
    weight_max_vel_theta: 1
    weight_max_vel_x: 2
    weight_obstacle: 100
    weight_optimaltime: 1
    weight_shortest_path: 0
    weight_viapoint: 1
    wheelbase: 0.266
    xy_goal_tolerance: 0.3
    yaw_goal_tolerance: 0.16
  base_global_planner: global_planner/GlobalPlanner
  base_local_planner: base_local_planner/TrajectoryPlannerROS
  controller_frequency: 5.0
  controller_patience: 15.0
  global_costmap:
    always_send_full_costmap: true
    footprint_padding: 0.0
    global_frame: map
    inflation_layer: {cost_scaling_factor: 10.0, enabled: true, inflation_radius: 0.5}
    map_type: costmap
    obstacle_layer:
      combination_method: 1
      enabled: true
      inflation_radius: 0.5
      observation_sources: point_cloud_sensorA
      obstacle_range: 10.0
      point_cloud_sensorA: {clearing: true, data_type: PointCloud2, marking: true,
        sensor_frame: /apnapioneer3at/MultiSense_S21_meta_range_finder, topic: /apnapioneer3at/MultiSense_S21_meta_range_finder/point_cloud_segmented}
      raytrace_range: 4.0
      track_unknown_space: true
    plugins:
    - {name: static_layer, type: 'costmap_2d::StaticLayer'}
    - {name: obstacle_layer, type: 'costmap_2d::VoxelLayer'}
    - {name: inflation_layer, type: 'costmap_2d::InflationLayer'}
    publish_frequency: 0.5
    robot_base_frame: base_link
    robot_radius: 0.25
    static_layer: {enabled: true, map_topic: /map}
    static_map: true
    transform_tolerance: 0.5
    update_frequency: 1.0
  local_costmap:
    always_send_full_costmap: true
    footprint_padding: 0.0
    global_frame: map
    height: 5
    inflation_layer: {cost_scaling_factor: 10.0, enabled: true, inflation_radius: 0.5}
    map_type: costmap
    obstacle_layer:
      combination_method: 1
      enabled: true
      inflation_radius: 0.5
      observation_sources: point_cloud_sensorA
      obstacle_range: 10.0
      point_cloud_sensorA: {clearing: true, data_type: PointCloud2, marking: true,
        sensor_frame: /apnapioneer3at/MultiSense_S21_meta_range_finder, topic: /apnapioneer3at/MultiSense_S21_meta_range_finder/point_cloud_segmented}
      raytrace_range: 4.0
      track_unknown_space: true
    plugins:
    - {name: static_layer, type: 'costmap_2d::StaticLayer'}
    - {name: obstacle_layer, type: 'costmap_2d::ObstacleLayer'}
    publish_frequency: 2.0
    resolution: 0.1
    robot_base_frame: base_link
    robot_radius: 0.25
    rolling_window: true
    static_layer: {enabled: true, map_topic: /map}
    static_map: true
    transform_tolerance: 0.5
    update_frequency: 5.0
    width: 5
  planner_frequency: 1.0
  planner_patience: 5.0
passthrough: {filter_field_name: z, filter_limit_max: 4.5, filter_limit_min: 0.01,
  filter_limit_negative: false, input_frame: '', keep_organized: false, output_frame: ''}
passthrough_below_ground: {filter_field_name: y, filter_limit_max: 999.0, filter_limit_min: 0.275,
  filter_limit_negative: false, input_frame: '', keep_organized: false, output_frame: ''}
passthrough_inverse: {filter_field_name: z, filter_limit_max: 10.9, filter_limit_min: 0.01,
  filter_limit_negative: true, input_frame: '', keep_organized: false, output_frame: ''}
rosdistro: 'kinetic

  '
roslaunch:
  uris: {host_hash_sys__38021: 'http://hash-sys:38021/'}
rosversion: '1.12.14

  '
run_id: a0d236fe-6470-11ea-a721-7cdd909f965b
system_name: hash
use_sim_time: true
visualization_path: /home/hash/catkin_ws/src/visualization
